#!/usr/bin/env python3
"""Inline the committed corpus and run outputs into data.bundle.js, and
assemble a single-file build of the whole report.

    python3 tools/build_bundle.py

Two outputs, both committed:

  data.bundle.js      loaded by index.html. Over http the report fetches the
                      JSON files directly; from file:// fetch is blocked, so
                      this is the same data inlined. Either way the report
                      makes no request to another origin (NFR-05, RPT-01).

  risk-radar.html     the whole report as one file: markup, stylesheet,
                      script and data. Opens from a bare filesystem with no
                      server at all.
"""

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
from build import strip_static  # noqa: E402

WEEKS = [1, 2, 3, 4]


def read_json(*parts):
    with open(os.path.join(ROOT, *parts), encoding="utf-8") as fh:
        return json.load(fh)


def read_text(*parts):
    with open(os.path.join(ROOT, *parts), encoding="utf-8") as fh:
        return fh.read()


def read_tickets():
    import csv
    with open(os.path.join(ROOT, "data", "tickets.csv"), newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def bundle():
    return {
        "registers": {str(w): read_json("runs", f"week-{w}-register.json") for w in WEEKS},
        "transcripts": {str(w): read_json("data", "transcripts", f"week-{w}.json") for w in WEEKS},
        "tickets": read_tickets(),
        "board": read_json("data", "board.json"),
    }


def js_literal(payload):
    """JSON is not a strict JS subset: U+2028 and U+2029 are valid in a JSON
    string and terminate a JS line. Escape them, and escape '<' so the
    payload can never close the script element that carries it."""
    text = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    return (text.replace(" ", "\\u2028")
                .replace(" ", "\\u2029")
                .replace("<", "\\u003c"))


def write_bundle(payload):
    path = os.path.join(ROOT, "data.bundle.js")
    body = (
        "/* GENERATED by tools/build_bundle.py — do not edit.\n"
        " * The committed corpus and run outputs, inlined so the report opens\n"
        " * from file:// with no server and no request to any other origin. */\n"
        "window.RISK_RADAR = " + js_literal(payload) + ";\n"
    )
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(body)
    return path, len(body.encode("utf-8"))


def write_single_file(payload):
    # The bundle is the data source here, so drop the painted week rather
    # than ship the same week twice.
    html = strip_static(read_text("index.html"))
    css = read_text("styles.css")
    app = read_text("app.js")

    html = html.replace(
        '<link rel="stylesheet" href="styles.css">',
        "<style>\n" + css + "\n</style>",
    )
    html = html.replace(
        '<script src="app.js"></script>',
        "<script>window.RISK_RADAR = " + js_literal(payload) + ";</script>\n"
        "<script>\n" + app.replace("</script", "<\\/script") + "\n</script>",
    )
    html = html.replace(
        "<title>Risk Radar — delivery register</title>",
        "<title>Risk Radar — delivery register</title>\n"
        "<!-- Single-file build. Regenerate with python3 tools/build_bundle.py -->",
    )
    path = os.path.join(ROOT, "risk-radar.html")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(html)
    return path, len(html.encode("utf-8"))


def main():
    payload = bundle()
    for path, size in (write_bundle(payload), write_single_file(payload)):
        print(f"{os.path.relpath(path, ROOT):<20} {size / 1024:7.1f} KB")

    # NFR-01. The default week is painted into index.html, so a first load is
    # the shell alone: no register JSON is fetched until the reader switches
    # week. Transfer is what counts, and every static host compresses.
    import gzip

    shell = ["index.html", "styles.css", "app.js"]
    raw = sum(os.path.getsize(os.path.join(ROOT, f)) for f in shell)
    comp = sum(len(gzip.compress(open(os.path.join(ROOT, f), "rb").read(), 9)) for f in shell)
    print(f"\nfirst load over http: {raw / 1024:.1f} KB raw, {comp / 1024:.1f} KB compressed"
          f"   {'under' if comp < 150 * 1024 else 'OVER'} the 150 KB NFR-01 budget")
    print("  " + "  ".join(f"{f} {os.path.getsize(os.path.join(ROOT, f)) / 1024:.0f}K" for f in shell))
    print("  switching week fetches that week's register only")


if __name__ == "__main__":
    main()
